export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  AUTH_CALLBACK: '/auth/callback',
  COMPLETE_PROFILE: '/complete-profile',
  DASHBOARD: '/student/dashboard', // student dashboard (kept for backwards-compat)
  STUDENT_DASHBOARD: '/student/dashboard',
  VIDEO_INTERVIEW: '/video-interview',
  VIDEO_INTERVIEW_REPORTS: '/video-interview-reports',
  INTERVIEW_INTERFACE: '/interview-interface',
  /** Dev/test duplicate of interview UI; same state contract as `INTERVIEW_INTERFACE`. */
  TEST_VIDEO: '/test-video',
  /** Experimental routes (authenticated AppLayout). */
  EXPERIMENTAL_TEST_VIDEO: '/experimental/test-video',
  EXPERIMENTAL_TEST_FEEDBACK: '/experimental/test-feedback',
  LEARNING: '/learning',
  LEARNING_ARRAYS: '/learning/arrays',
  RESUME_ANALYSIS: '/resume-analysis',
  RESUME_ANALYSIS_REPORTS: '/resume-analysis-reports',
  RESUME_GENERATION: '/resume-generation',
  ACCOUNT: '/account',
  FEEDBACK: '/feedback',
  FEEDBACK_HISTORY: '/feedback-history/:interviewId',
  /** Saved resume analysis report (same UI as /feedback, URL-addressable like feedback-history) */
  RESUME_FEEDBACK_HISTORY: '/resume-feedback/:analysisId',
  ABOUT: '/about',
  CONTACT: '/contact',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_OF_SERVICE: '/terms-of-service',
  VIDEO_INTERVIEWS_LANDING: '/video-interviews',
  RESUME_LANDING: '/resume',
  LANDING_DASHBOARD: '/dashboard',
  PRICING: '/pricing',
  STUDENT_INTERVIEW_HISTORY: '/student/interview-history',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_INTERVIEW_THUMBNAILS: '/admin/interview-thumbnails',
  ORG_SETUP: '/org/setup',
  ORG_DASHBOARD: '/org/dashboard',
  ORG_TEACHER_DETAIL: '/org/teachers/:teacherUserId',
  ORG_CLASS_DETAIL: '/org/classes/:classId',
  ORG_STUDENT_DETAIL: '/org/students/:studentUserId',
  TEACHER_ONBOARDING: '/teacher/onboarding',
  TEACHER_CLASSES: '/teacher/classes',
  TEACHER_CLASS_DETAIL: '/teacher/classes/:classId',
  TEACHER_STUDENT_DETAIL: '/teacher/students/:studentUserId',
  STUDENT_MY_CLASSES: '/student/my-classes',
  STUDENT_CLASS_DETAIL: '/student/classes/:classId',
  NOT_FOUND: '*',
} as const;
