export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  AUTH_CALLBACK: '/auth/callback',
  COMPLETE_PROFILE: '/complete-profile',
  DASHBOARD: '/student/dashboard', // student dashboard (kept for backwards-compat)
  STUDENT_DASHBOARD: '/student/dashboard',
  VIDEO_INTERVIEW: '/video-interview',
  VIDEO_INTERVIEW_REPORTS: '/video-interview-reports',
  INTERVIEW_INTERFACE: '/interview-interface',
  LEARNING: '/learning',
  LEARNING_ARRAYS: '/learning/arrays',
  RESUME_ANALYSIS: '/resume-analysis',
  RESUME_ANALYSIS_REPORTS: '/resume-analysis-reports',
  RESUME_GENERATION: '/resume-generation',
  ACCOUNT: '/account',
  FEEDBACK: '/feedback',
  ABOUT: '/about',
  CONTACT: '/contact',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_OF_SERVICE: '/terms-of-service',
  VIDEO_INTERVIEWS_LANDING: '/video-interviews',
  RESUME_LANDING: '/resume',
  LANDING_DASHBOARD: '/dashboard',
  TEACHER_CLASSES: '/teacher/classes',
  TEACHER_SCHEDULE: '/teacher/schedule',
  TEACHER_STUDENTS: '/teacher/students',
  STUDENT_CLASSES: '/student/classes',
  STUDENT_INTERVIEW_HISTORY: '/student/interview-history',
  TEACHER_DASHBOARD: '/teacher/dashboard',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  NOT_FOUND: '*',
} as const;
